name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: read
  checks: write
  security-events: write

jobs:

  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  checkov-scan:
    needs: scan
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        output_format: cli,sarif
        output_file_path: console,results.sarif
        skip_check: CKV_DOCKER_2 
        skip_framework: helm
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: results.sarif
          
  build:
    needs: checkov-scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build apps --file apps/Dockerfile --tag cash-api:$(date +%s)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Tag the Docker image
        run: docker tag cash-api:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/cash-api:$(date +%s)
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cash-api:$(date +%s)